import type { Metadata } from 'next'
import FadeInWhenVisible from '@/components/FadeInWhenVisible'

export const metadata: Metadata = {
  title: 'Terms of Service | FoodWise GLP-1 Meal Planner',
  description: 'Terms of service for FoodWise, the GLP-1 meal planning app.',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0A1628] pt-20 pb-30">
      <div className="max-w-[720px] mx-auto px-4 sm:px-6">
        <FadeInWhenVisible>
          <div className="mb-10">
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-[-0.03em] text-white mb-4">
              Terms of Service
            </h1>
          </div>
        </FadeInWhenVisible>

        {/* Medical disclaimer callout */}
        <FadeInWhenVisible>
          <div className="mb-10 bg-[#1D9E75]/10 border border-[#1D9E75]/40 rounded-2xl p-6">
            <p className="text-[#A8F0D8] font-semibold text-sm uppercase tracking-wider mb-2">
              ⚕️ Medical Disclaimer
            </p>
            <p className="text-[#94A3B8] leading-relaxed">
              FoodWise is not a medical app and is not a substitute for professional medical
              advice, diagnosis, or treatment. Always consult your prescribing physician before
              making changes to your diet or medication. Meal plans generated by FoodWise are
              for general nutrition guidance only and have not been evaluated by the FDA.
            </p>
          </div>
        </FadeInWhenVisible>

        <div className="space-y-8" style={{ fontSize: 16, lineHeight: 1.7, color: '#444444' }}>
          <Section title="1. Acceptance">
            <p>By using FoodWise you agree to these terms.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              FoodWise is a nutrition guidance app for GLP-1 medication users. It generates
              AI-powered meal plans and tracks symptoms. It is not a medical device and does
              not provide medical advice.
            </p>
          </Section>

          <Section title="3. Subscriptions and Payments">
            <ul className="list-disc list-inside mt-2 space-y-2 ml-2">
              <li>FoodWise Pro: $12.99/month or $99/year, processed by Apple via in-app purchase.</li>
              <li>7-day free trial for new subscribers.</li>
              <li>Cancel anytime in iOS Settings.</li>
              <li>No refunds except as required by Apple&apos;s standard policy.</li>
            </ul>
          </Section>

          <Section title="4. Free Tier Limits">
            <p>Up to 3 meal plans per month on the free tier.</p>
          </Section>

          <Section title="5. User Conduct">
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-3 space-y-2 ml-2">
              <li>Reverse-engineer or decompile the app</li>
              <li>Scrape AI outputs for commercial use without written permission</li>
              <li>Use the app for any unlawful purpose</li>
            </ul>
          </Section>

          <Section title="6. Intellectual Property">
            <p>
              FoodWise and its content are owned by [Company Name]. AI-generated meal plans
              are for personal use only.
            </p>
            <p className="mt-2 text-sm text-[#94A3B8]">
              Before submission: replace [Company Name] with your legal entity name.
            </p>
          </Section>

          <Section title="7. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, FoodWise is not liable for any health
              outcomes from following the app&apos;s recommendations.
            </p>
          </Section>

          <Section title="8. Governing Law">
            <p>Governed by the laws of [State], United States.</p>
            <p className="mt-2 text-sm text-[#94A3B8]">
              Before submission: replace [State] with your state of incorporation.
            </p>
          </Section>

          <Section title="9. Changes">
            <p>
              Material changes will be notified via push notification or email. Continued use
              after changes constitutes acceptance.
            </p>
          </Section>

          <Section title="10. Contact">
            <p>
              <a href="mailto:support@foodwise.app" className="text-[#1D9E75] hover:text-[#A8F0D8] transition-colors">
                support@foodwise.app
              </a>
            </p>
          </Section>
        </div>
      </div>
    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <FadeInWhenVisible>
      <div className="bg-[rgba(15,32,64,0.6)] backdrop-blur-xl border border-white/10 rounded-2xl p-8">
        <h2 className="text-xl font-bold text-white mb-4">{title}</h2>
        <div className="space-y-3">{children}</div>
      </div>
    </FadeInWhenVisible>
  )
}
